<?xml version="1.0" encoding="UTF-8" ?>
<testsuites disabled="0" errors="0" failures="2" tests="2" time="200.098">
 <testsuite name="demo login" timestamp="2021-07-06T17:27:43" hostname="localhost" time="200.095" errors="0" tests="1" skipped="0" disabled="0" failures="2">
  <testcase classname="demo login" name="login test" time="200.083">
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\nb49\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)]]>
   </failure>
   <failure type="exception" message="Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."><![CDATA[Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at Timeout._onTimeout (C:\Users\nb49\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)]]>
   </failure>
  </testcase>
 </testsuite>
 <testsuite name="CSP demo login" timestamp="2021-07-06T17:31:03" hostname="localhost" time="0.003" errors="0" tests="1" skipped="0" disabled="0" failures="0">
  <testcase classname="CSP demo login" name="CSP login test" time="0.002" />
 </testsuite>
</testsuites>